---
title: Documentation
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  docs:
    title: docs
    output: true
    
defaults:
  - scope:
      path: "docs"
      type: "Pages"
